name:                hs-picturefarm
version:             0.1.0.0
github:              "gabiseabra/hs-picturefarm"
license:             BSD3
author:              "gabiseabra (Gabriela Seabra)"
maintainer:          "gabriela.lima.se@gmail.com"
copyright:           "2020 gabiseabra (Gabriela Seabra)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gabiseabra/hs-picturefarm#readme>

default-extensions:
- TemplateHaskell
- QuasiQuotes
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
- TypeFamilies
- NamedFieldPuns
- DisambiguateRecordFields
- DuplicateRecordFields
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- composition-prelude
- errors
- mtl
- data-default-class
- text
- tuple
- either
- uuid
- bytestring
- string-conversions
- rawstring-qm
- resource-pool
- transformers
- envy
- load-env
- postgresql-simple
- postgresql-simple-url
- postgresql-simple-named
- morpheus-graphql
- http-types
- scotty
- wai
- warp

library:
  source-dirs: src

executables:
  hs-picturefarm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-picturefarm

tests:
  hs-picturefarm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-picturefarm
    - cryptohash-md5
    - aeson-qq
    - hspec
    - hspec-discover
    - hspec-wai
    - hspec-wai-json
    - wai-extra
    - async